-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 18:50:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema art-gallery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema art-gallery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `art-gallery` DEFAULT CHARACTER SET utf8mb4 ;
USE `art-gallery` ;

-- -----------------------------------------------------
-- Table `art-gallery`.`Picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `art-gallery`.`Picture` (
  `IdPicture` INT NOT NULL AUTO_INCREMENT,
  `Price` DECIMAL(19,4) NOT NULL,
  `Autor` VARCHAR(45) NOT NULL DEFAULT 'Anonymous',
  `Stock` INT NOT NULL,
  PRIMARY KEY (`IdPicture`),
  UNIQUE INDEX `IdPicture_UNIQUE` (`IdPicture` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `art-gallery`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `art-gallery`.`Client` (
  `IdClient` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Nie` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`IdClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `art-gallery`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `art-gallery`.`Sales` (
  `IdSales` INT NOT NULL AUTO_INCREMENT,
  `PictureId` INT NOT NULL,
  `ClientId` INT NOT NULL,
  PRIMARY KEY (`IdSales`),
  INDEX `pictureId_idx` (`PictureId` ASC),
  INDEX `clientId_idx` (`ClientId` ASC),
  CONSTRAINT `PictureId`
    FOREIGN KEY (`PictureId`)
    REFERENCES `art-gallery`.`Picture` (`IdPicture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClientId`
    FOREIGN KEY (`ClientId`)
    REFERENCES `art-gallery`.`Client` (`IdClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
